spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password:
  jpa:
    show-sql: true

  jwt:
    secretKey: ${JWT_SECRET}
    accessTokenExpiration: 900
    refreshTokenExpiration: 604800

  jackson:
    deserialization:
      fail-on-unknown-properties: true